import AppKit
import Observation

@Observable
final class ClipboardMonitor {
    var items: [ClipboardItem] = []
    var snippets: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let store = JSONFileStore<ClipboardItem>(fileName: "clipboard_history.json", label: "clipboard history")
    private let snippetStore = JSONFileStore<ClipboardItem>(fileName: "snippets.json", label: "snippets")
    private let imageProcessingQueue = DispatchQueue(label: "com.clippy.imageprocessing", qos: .utility)
    private let maxItems = 200
    private var ignoreNextChange = false
    private var lastPurgeCheck: Date = .distantPast
    private var lastClipboardChangeTime: Date = .distantPast

    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init() {
        items = store.load()
        snippets = snippetStore.load()
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        purgeExpiredItems()
        reconcileImageFiles()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
    }

    /// At launch: delete image files no longer referenced by any item, then
    /// re-save so legacy inline-image migrations are recorded and any
    /// pre-existing plaintext sensitive entries are re-encrypted at rest.
    private func reconcileImageFiles() {
        var referenced = Set<String>()
        for item in items + snippets where item.contentType == .image {
            if let name = item.imageFileName { referenced.insert(name) }
        }
        ImageStore.shared.pruneUnreferenced(keeping: referenced)

        if !items.isEmpty { store.save(items) }
        if !snippets.isEmpty { snippetStore.save(snippets) }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        store.saveImmediately(items)
        snippetStore.saveImmediately(snippets)
    }

    func filteredItems(searchText: String) -> [ClipboardItem] {
        guard !searchText.isEmpty else { return items }
        return items.filter { item in
            switch item.contentType {
            case .text:
                return item.textContent?.localizedCaseInsensitiveContains(searchText) ?? false
            case .image:
                return "image".localizedCaseInsensitiveContains(searchText)
            }
        }
    }

    func deleteItem(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        deleteImageFile(for: item)
        store.save(items)
    }

    func clearAll() {
        deleteImageFiles(for: items)
        items.removeAll()
        store.save(items)
    }

    func clearItems(inLastMinutes minutes: Int) {
        let cutoff = Date().addingTimeInterval(-TimeInterval(minutes * 60))
        deleteImageFiles(for: items.filter { $0.timestamp >= cutoff })
        items.removeAll { $0.timestamp >= cutoff }
        store.save(items)
    }

    func setIgnoreNextChange() {
        ignoreNextChange = true
    }

    // MARK: - Snippets

    func saveAsSnippet(_ item: ClipboardItem) {
        // Avoid duplicate snippets
        if snippets.contains(where: { $0.contentType == item.contentType && $0.textContent == item.textContent && $0.imageFileName == item.imageFileName }) {
            return
        }
        // Give image snippets their own copy of the file so purging history
        // does not delete a file the snippet still references.
        var toSave = item
        if item.contentType == .image,
           let name = item.imageFileName,
           let copied = ImageStore.shared.copy(name) {
            toSave = ClipboardItem.image(fileName: copied, sourceAppName: item.sourceAppName, sourceAppBundleID: item.sourceAppBundleID)
        }
        snippets.insert(toSave, at: 0)
        snippetStore.save(snippets)
    }

    func deleteSnippet(_ item: ClipboardItem) {
        snippets.removeAll { $0.id == item.id }
        deleteImageFile(for: item)
        snippetStore.save(snippets)
    }

    // MARK: - Private

    private func purgeExpiredItems() {
        let cutoff = Date().addingTimeInterval(-AppSettings.shared.retentionPeriod.timeInterval)
        let expired = items.filter { $0.timestamp < cutoff }
        guard !expired.isEmpty else { return }
        deleteImageFiles(for: expired)
        items.removeAll { $0.timestamp < cutoff }
        store.save(items)
    }

    private func checkClipboard() {
        // Periodic retention purge (every 60s)
        if Date().timeIntervalSince(lastPurgeCheck) > 60 {
            purgeExpiredItems()
            lastPurgeCheck = Date()
        }

        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount

        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        // Skip concealed, transient, or auto-generated clipboard data
        let pasteboardTypes = pasteboard.types ?? []
        if Self.sensitiveTypes.contains(where: { pasteboardTypes.contains($0) }) {
            return
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication

        // Skip ignored apps
        if let bundleID = sourceApp?.bundleIdentifier,
           AppSettings.shared.ignoredAppBundleIDs.contains(bundleID) {
            return
        }

        let now = Date()
        let timeSinceLastChange = now.timeIntervalSince(lastClipboardChangeTime)
        lastClipboardChangeTime = now

        // Check for image first
        if let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png) {
            // Decode + re-encode + write the file off the main thread; the raw
            // pasteboard bytes and source app strings are all we capture here.
            let sourceName = sourceApp?.localizedName
            let sourceBundle = sourceApp?.bundleIdentifier
            imageProcessingQueue.async { [weak self] in
                guard let pngData = Self.pngData(from: imageData) else { return }
                let fileName = ImageStore.shared.write(pngData)
                let item = ClipboardItem.image(fileName: fileName, sourceAppName: sourceName, sourceAppBundleID: sourceBundle)
                DispatchQueue.main.async {
                    self?.insertItem(item)
                }
            }
        } else if let string = pasteboard.string(forType: .string), !string.isEmpty {
            // Avoid duplicate consecutive text
            if let lastText = items.first?.textContent, lastText == string {
                return
            }

            // Merge mode: append to most recent item if within time window
            let settings = AppSettings.shared
            if settings.isMergeEnabled,
               timeSinceLastChange < settings.mergeWindowSeconds,
               let first = items.first, first.contentType == .text,
               let existingText = first.textContent {
                let merged = existingText + "\n" + string
                items[0] = ClipboardItem(
                    id: first.id,
                    contentType: .text,
                    textContent: merged,
                    imageFileName: nil,
                    timestamp: first.timestamp,
                    sourceAppName: first.sourceAppName,
                    sourceAppBundleID: first.sourceAppBundleID
                )
                store.save(items)
                return
            }

            let item = ClipboardItem.text(string, sourceApp: sourceApp)
            insertItem(item)
        }
    }

    private func insertItem(_ item: ClipboardItem) {
        items.insert(item, at: 0)
        if items.count > maxItems {
            deleteImageFiles(for: Array(items[maxItems...]))
            items.removeLast(items.count - maxItems)
        }
        store.save(items)
    }

    // MARK: - Image file cleanup

    private func deleteImageFile(for item: ClipboardItem) {
        if item.contentType == .image, let name = item.imageFileName {
            ImageStore.shared.delete(name)
        }
    }

    private func deleteImageFiles(for items: [ClipboardItem]) {
        for item in items {
            deleteImageFile(for: item)
        }
    }

    private static func pngData(from raw: Data) -> Data? {
        guard let bitmapRep = NSBitmapImageRep(data: raw) else { return nil }
        return bitmapRep.representation(using: .png, properties: [.compressionFactor: 0.8])
    }
}
