import AppKit
import Observation

@Observable
final class ClipboardMonitor {
    var items: [ClipboardItem] = []

    private var timer: Timer?
    private var lastChangeCount: Int = 0
    private let store = ClipboardStore()
    private let maxItems = 200
    private var ignoreNextChange = false
    private var lastPurgeCheck: Date = .distantPast

    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    init() {
        items = store.load()
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        purgeExpiredItems()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkClipboard()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func filteredItems(searchText: String) -> [ClipboardItem] {
        guard !searchText.isEmpty else { return items }
        return items.filter { item in
            switch item.contentType {
            case .text:
                return item.textContent?.localizedCaseInsensitiveContains(searchText) ?? false
            case .image:
                return "image".localizedCaseInsensitiveContains(searchText)
            }
        }
    }

    func deleteItem(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        store.save(items)
    }

    func clearAll() {
        items.removeAll()
        store.save(items)
    }

    func clearItems(inLastMinutes minutes: Int) {
        let cutoff = Date().addingTimeInterval(-TimeInterval(minutes * 60))
        items.removeAll { $0.timestamp >= cutoff }
        store.save(items)
    }

    func setIgnoreNextChange() {
        ignoreNextChange = true
    }

    // MARK: - Private

    private func purgeExpiredItems() {
        let cutoff = Date().addingTimeInterval(-AppSettings.shared.retentionPeriod.timeInterval)
        let countBefore = items.count
        items.removeAll { $0.timestamp < cutoff }
        if items.count != countBefore {
            store.save(items)
        }
    }

    private func checkClipboard() {
        // Periodic retention purge (every 60s)
        if Date().timeIntervalSince(lastPurgeCheck) > 60 {
            purgeExpiredItems()
            lastPurgeCheck = Date()
        }

        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount

        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        if ignoreNextChange {
            ignoreNextChange = false
            return
        }

        // Skip concealed, transient, or auto-generated clipboard data
        let pasteboardTypes = pasteboard.types ?? []
        if Self.sensitiveTypes.contains(where: { pasteboardTypes.contains($0) }) {
            return
        }

        let sourceApp = NSWorkspace.shared.frontmostApplication

        // Check for image first
        if let imageData = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png) {
            if let bitmapRep = NSBitmapImageRep(data: imageData),
               let pngData = bitmapRep.representation(using: .png, properties: [.compressionFactor: 0.8]) {
                let item = ClipboardItem.image(pngData, sourceApp: sourceApp)
                insertItem(item)
            }
        } else if let string = pasteboard.string(forType: .string), !string.isEmpty {
            // Avoid duplicate consecutive text
            if let lastText = items.first?.textContent, lastText == string {
                return
            }
            let item = ClipboardItem.text(string, sourceApp: sourceApp)
            insertItem(item)
        }
    }

    private func insertItem(_ item: ClipboardItem) {
        items.insert(item, at: 0)
        if items.count > maxItems {
            items = Array(items.prefix(maxItems))
        }
        store.save(items)
    }
}
